make:
	cd plus; make
	cd fact; make
	cd calc; make
	cd let; make
	cd hello; make
	cd link; make
	cd link2; make
	cd lambda; make

clean:
	cd plus; make clean
	cd fact; make clean
	cd calc; make clean
	cd let; make clean
	cd hello; make clean
	cd link; make clean
	cd link2; make clean
	cd lambda; make clean

