all:
	gplc hello.pl
	gplc add.pl
	gplc add2.pl
	gplc calc.pl
	gplc calc2.pl
	gplc fact.pl
	gplc list.pl
	gplc strlist.pl
	gplc test01.pl
	gplc sum.pl

clean:
	rm -rf hello add add2 calc calc2 fact list strlist test01 seqprover sum

