pandoc title.txt \
  README.md \
  abstract.md \
  chap01/README.md \
  chap02/README.md \
  chap03/README.md \
  chap04/README.md \
  chap05/README.md \
  chap06/README.md \
  chap07/README.md \
  chap07/README_1.md \
  chap07/README_2.md \
  chap07/README_3.md \
  chap07/README_4.md \
  chap08/README.md \
  chap09/README.md \
  chap10/README.md \
  chap11/README.md \
  chap11/README_1.md \
  chap11/README_2.md \
  chap11/README_3.md \
  chap11/README_4.md \
  chap11/README_5.md \
  chap11/README_5_1.md \
  chap11/README_6.md \
  chap11/README_6_1.md \
  chap11/README_6_2.md \
  chap11/README_6_3.md \
  chap11/README_6_4.md \
  chap12/README.md \
  acknowledgments.md \
  references.md \
  footnotes.md \
  -o thih.epub \
  --epub-stylesheet=epub.css --smart
open thih.epub
