#!/usr/local/bin/php
<?php

ob_start();
  system("ocamldep ".$argv[1]);
$f = ob_get_contents();
ob_end_clean();

$s = array();
preg_replace_callback("/([^ ]+)\\.cmo/",
  function($m) use(&$s) {
    $s[$m[1].".ml"] = $m[1].".cmo";
    return "";
  },
  $f
);
$ss = array_keys($s);
$cmd = implode(" ", $ss)."\n";
ob_start();
system("ocamldep -sort $cmd");

$f = ob_get_contents();
ob_end_clean();

$fs = array();
foreach(preg_split("/ +/", $f) as $v) {
  if(preg_match("/^\\s*\$/", $v) > 0) continue;
  if(preg_match("/\\.ml\$/", $v) < 1) continue;
  $fs[] = $v;
}

var_export($fs);

$all = "";
$debug = false;
    foreach($fs as $file) {
        if (preg_match("/\\.ml\$/", $file) < 1) continue;
        $md = preg_replace("/\\.ml\$/", ".md", $file);
        $src = file_get_contents($file);
        $a = "";
        preg_replace_callback("/\\(\\*\\|(.*?)\\*\\)/s",
            function($m)use(&$a) {
                $a .= $m[1];
                return "";
            },
            $src
        );
        if($debug) {
            echo $md."\n";
            echo $a."\n";
        }
        file_put_contents($md, $a);
        $all .= $a;
    }

file_put_contents("README.md", $all);
