all:
	patscc -DATS_MEMALLOC_LIBC -L$(PATSHOME)/ccomp/atslib/lib -latslib parsec.dats ast.dats parser.dats main.dats -o main; ./main a.txt

ATS-Postiats:
	git clone https://github.com/githwxi/ATS-Postiats
