staload "libats/ML/SATS/basis.sats"
staload "libats/ML/SATS/string.sats"
staload "libats/ML/DATS/string.dats"
staload "libats/ML/SATS/list0.sats"

#include "peg.hats"
staload "peg.dats"
#include "syntax.hats"
staload "syntax.dats"
staload "parser.sats"
staload STDLIB = "libc/SATS/stdlib.sats"
