staload "libats/ML/SATS/basis.sats"
staload "libats/ML/SATS/string.sats"
staload "libats/ML/DATS/string.dats"
staload "libats/ML/SATS/list0.sats"

#include "parsec.hats"
staload "parsec.dats"
#include "ast.hats"
staload "ast.dats"
staload "parser.sats"
staload STDLIB = "libc/SATS/stdlib.sats"
