/*
**
** The C code is generated by ATS/Postiats
** The starting compilation time is: 2015-10-19: 21h:12m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER
//
#include _ATS_CCOMP_PRELUDE_USER
//
#endif /* _ATS_CCOMP_PRELUDE_USER */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2
//
#include _ATS_CCOMP_PRELUDE_USER2
//
#endif /* _ATS_CCOMP_PRELUDE_USER2 */

/*
staload-prologues(beg)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/integer_ptr.dats: 1639(line=51, offs=1) -- 1678(line=51, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/integer_fixed.dats: 1641(line=51, offs=1) -- 1680(line=51, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/char.dats: 1610(line=48, offs=1) -- 1649(line=48, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/memory.dats: 1410(line=38, offs=1) -- 1449(line=39, offs=32)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/string.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/strptr.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/strptr.dats: 1671(line=52, offs=1) -- 1718(line=52, offs=48)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats: 1613(line=48, offs=1) -- 1652(line=48, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats: 1675(line=52, offs=1) -- 1722(line=52, offs=48)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats: 1745(line=56, offs=1) -- 1783(line=56, offs=39)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libc/SATS/stdio.sats: 1898(line=62, offs=1) -- 1940(line=64, offs=27)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats: 1861(line=61, offs=1) -- 1901(line=61, offs=41)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libc/sys/SATS/stat.sats: 1390(line=36, offs=1) -- 1431(line=38, offs=3)
*/

#include "libc/sys/CATS/stat.cats"
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libc/sys/SATS/stat.sats: 1712(line=52, offs=1) -- 1754(line=53, offs=35)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats: 15323(line=844, offs=1) -- 15353(line=844, offs=31)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libc/SATS/stdio.sats: 1898(line=62, offs=1) -- 1940(line=64, offs=27)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/list.dats: 1527(line=44, offs=1) -- 1566(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/list.dats: 1567(line=45, offs=1) -- 1613(line=45, offs=47)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/list_vt.dats: 1536(line=44, offs=1) -- 1575(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/stream.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/stream_vt.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/tostring.dats: 1528(line=44, offs=1) -- 1567(line=45, offs=32)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/checkast.dats: 1531(line=44, offs=1) -- 1570(line=45, offs=32)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libc/SATS/stdlib.sats: 1389(line=36, offs=1) -- 1428(line=38, offs=3)
*/

#include "libc/CATS/stdlib.cats"
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libc/SATS/stdlib.sats: 1760(line=54, offs=1) -- 1800(line=55, offs=33)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_fprint_string)
ATSdyncst_mac(atspre_FILE_stdout)
ATSdyncst_mac(atspre_fprint_newline)
ATSdyncst_mac(atslib_system)
ATSdyncst_mac(atspre_add_ptr0_bsz)
ATSdyncst_mac(atspre_print_string)
ATSdyncst_mac(atspre_print_ptr)
ATSdyncst_mac(atspre_print_newline)
ATSdyncst_mac(atspre_g1int2uint_int_size)
ATSdyncst_mac(atspre_g1uint_gt_size)
ATSdyncst_mac(atspre_g1uint_pred_size)
ATSdyncst_mac(atspre_g1uint_sub_size)
ATSdyncst_mac(atspre_g1int_sub_int)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
ATSstatic()
atsvoid_t0ype
fsed_0(atstkind_type(atstype_ptrk)) ;

#if(0)
ATSextern()
atsvoid_t0ype
mainats_argc_argv_0(atstkind_t0ype(atstype_int), atsrefarg0_type(atstkind_type(atstype_ptrk))) ;
#endif // end of [QUALIFIED]

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__ptr0_succ__2(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__ptr0_succ__2__1(atstkind_type(atstype_ptrk)) ;

#if(0)
#if(0)
ATSextern()
atsvoid_t0ype
ATSLIB_056_prelude__array_foreach__fwork__4(atsrefarg1_type(atstkind_type(atstype_ptrk)), atsrefarg1_type(atstyvar_type(env))) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__arrayref_foreach__5(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_size)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__arrayref_foreach__5__1(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_size)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__arrayref_foreach_env__7(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_size), atsrefarg1_type(atstyvar_type(env))) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__arrayref_foreach_env__7__1(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_size), atsrefarg1_type(atsvoid_t0ype)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__array_foreach_env__9(atsrefarg1_type(atstyarr_type(atstyvar_type(a))), atstkind_t0ype(atstype_size), atsrefarg1_type(atstyvar_type(env))) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstatic()
atstkind_t0ype(atstype_size)
loop_10__10(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_size), atsrefarg1_type(atstyvar_type(env))) ;
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__array_foreach_env__9__1(atsrefarg1_type(atstyarr_type(atstkind_type(atstype_ptrk))), atstkind_t0ype(atstype_size), atsrefarg1_type(atsvoid_t0ype)) ;

ATSstatic()
atstkind_t0ype(atstype_size)
loop_10__10__1(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_size), atsrefarg1_type(atsvoid_t0ype)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g1uint_int__13(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g1uint_int__13__1(atstkind_t0ype(atstype_size), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__array_foreach__cont__17(atsrefarg1_type(atstyvar_type(a)), atsrefarg1_type(atstyvar_type(env))) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__array_foreach__cont__17__1(atsrefarg1_type(atstkind_type(atstype_ptrk)), atsrefarg1_type(atsvoid_t0ype)) ;

ATSstatic()
atsvoid_t0ype
ATSLIB_056_prelude__array_foreach__fwork__4__1(atsrefarg1_type(atstkind_type(atstype_ptrk)), atsrefarg1_type(atsvoid_t0ype)) ;

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__ptr1_succ__20(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__ptr1_succ__20__1(atstkind_type(atstype_ptrk)) ;

ATSstatic()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__ptr0_succ__2__2(atstkind_type(atstype_ptrk)) ;

/*
/Users/sakurai/git/docs/gc/ats_basic/cast.dats: 272(line=10, offs=5) -- 790(line=21, offs=4)
*/
/*
local: 
global: fsed_0$0(level=0)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
fsed_0(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret0) ;
ATStmpdec(tmpref1[1024], atstkind_t0ype(atstype_byte)) ;
ATStmpdec(tmp2, atstype_arrptr) ;
ATStmpdec(tmp3, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp4) ;
// ATStmpdec_void(tmp5) ;
// ATStmpdec_void(tmp6) ;
ATStmpdec(tmp7, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/cast.dats: 272(line=10, offs=5) -- 790(line=21, offs=4)
*/
ATSINSflab(__patsflab_fsed_0):
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/cast.dats: 300(line=10, offs=33) -- 790(line=21, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/cast.dats: 310(line=11, offs=7) -- 313(line=11, offs=10)
*/
/*
ATSINStmpdec(tmpref1) ;
*/
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/cast.dats: 316(line=11, offs=13) -- 332(line=11, offs=29)
*/
ATSINSmove(tmp2, tmpref1) ;
/* (*nothing*) */
/* (*nothing*) */
/* (*nothing*) */
/* (*nothing*) */
/* (*nothing*) */
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/cast.dats: 564(line=17, offs=11) -- 655(line=17, offs=102)
*/
ATSINSmove(tmp3, ATSextfcall(snprintf, (ATSPMVcastfn(cast, char*, ATSPMVptrof(tmpref1[0])), ATSPMVintrep(1024), ATSPMVstring("%s %s | %s %s > o_%s"), ATSPMVstring("cat"), ATSPMVcastfn(cast, char*, arg0), ATSPMVstring("sed"), ATSPMVstring("\ns/'><\\/BODY'/'><SCRIPT SRC=\".\\/assets\\/ATS2TUTORIAL-BOOK.js\"><\\/SCRIPT><\\/BODY'/\n"), ATSPMVcastfn(cast, char*, arg0)))) ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/cast.dats: 667(line=18, offs=12) -- 733(line=18, offs=78)
*/
ATSINSmove_void(tmp4, atspre_fprint_string(atspre_FILE_stdout, ATSPMVstring("fsed: command = "))) ;

/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/cast.dats: 667(line=18, offs=12) -- 733(line=18, offs=78)
*/
ATSINSmove_void(tmp5, atspre_fprint_string(atspre_FILE_stdout, ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), ATSPMVcastfn(cast, char*, ATSPMVptrof(tmpref1[0]))))) ;

/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/cast.dats: 667(line=18, offs=12) -- 733(line=18, offs=78)
*/
ATSINSmove_void(tmp6, atspre_fprint_newline(atspre_FILE_stdout)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/cast.dats: 739(line=20, offs=3) -- 786(line=20, offs=50)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/cast.dats: 739(line=20, offs=3) -- 786(line=20, offs=50)
*/
ATSINSmove(tmp7, atslib_system(ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), ATSPMVcastfn(cast, char*, ATSPMVptrof(tmpref1[0]))))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/cast.dats: 739(line=20, offs=3) -- 786(line=20, offs=50)
*/
ATSINSmove_void(tmpret0, ATSPMVempty()) ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/cast.dats: 739(line=20, offs=3) -- 786(line=20, offs=50)
*/
/*
INSletpop()
*/
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/cast.dats: 300(line=10, offs=33) -- 790(line=21, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret0) ;
} /* end of [fsed_0] */

/*
/Users/sakurai/git/docs/gc/ats_basic/cast.dats: 811(line=23, offs=20) -- 1085(line=29, offs=4)
*/
/*
local: fsed_0$0(level=0)
global: fsed_0$0(level=0), mainats_argc_argv_0$1$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
mainats_argc_argv_0(atstkind_t0ype(atstype_int) arg0, atsrefarg0_type(atstkind_type(atstype_ptrk)) arg1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret8) ;
ATStmpdec(tmp9, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp12) ;
// ATStmpdec_void(tmp13) ;
// ATStmpdec_void(tmp14) ;
ATStmpdec(tmp16, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp53, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp54, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/cast.dats: 802(line=23, offs=11) -- 1085(line=29, offs=4)
*/
ATSINSflab(__patsflab_main_argc_argv_0):
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/cast.dats: 826(line=23, offs=35) -- 1085(line=29, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/cast.dats: 844(line=24, offs=15) -- 887(line=24, offs=58)
*/
ATSINSmove(tmp9, ATSLIB_056_prelude__ptr0_succ__2__1(ATSPMVcastfn(castvwtp1, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg1)))) ;

/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/cast.dats: 899(line=25, offs=12) -- 923(line=25, offs=36)
*/
ATSINSmove_void(tmp12, atspre_print_string(ATSPMVstring("argv1"))) ;

/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/cast.dats: 899(line=25, offs=12) -- 923(line=25, offs=36)
*/
ATSINSmove_void(tmp13, atspre_print_ptr(tmp9)) ;

/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/cast.dats: 899(line=25, offs=12) -- 923(line=25, offs=36)
*/
ATSINSmove_void(tmp14, atspre_print_newline()) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/cast.dats: 998(line=28, offs=3) -- 1081(line=28, offs=86)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/cast.dats: 998(line=28, offs=3) -- 1081(line=28, offs=86)
*/
ATSINSmove(tmp54, atspre_g1int_sub_int(arg0, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/cast.dats: 998(line=28, offs=3) -- 1081(line=28, offs=86)
*/
ATSINSmove(tmp53, atspre_g1int2uint_int_size(tmp54)) ;

/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/cast.dats: 998(line=28, offs=3) -- 1081(line=28, offs=86)
*/
ATSINSmove(tmp16, ATSLIB_056_prelude__arrayref_foreach__5__1(ATSPMVcastfn(castvwtp1, atstkind_type(atstype_ptrk), ATSPMVrefarg0(tmp9)), tmp53)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/cast.dats: 998(line=28, offs=3) -- 1081(line=28, offs=86)
*/
ATSINSmove_void(tmpret8, ATSPMVempty()) ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/cast.dats: 998(line=28, offs=3) -- 1081(line=28, offs=86)
*/
/*
INSletpop()
*/
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/cast.dats: 826(line=23, offs=35) -- 1085(line=29, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret8) ;
} /* end of [mainats_argc_argv_0] */

#if(0)
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/pointer.dats: 1808(line=61, offs=11) -- 1840(line=61, offs=43)
*/
/*
local: 
global: ptr0_succ$2$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(4026)
tmparg = S2Evar(a(4026))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__ptr0_succ__2(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret10, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/pointer.dats({$PATSPRE}/DATS/pointer.dats): 1798(line=61, offs=1) -- 1840(line=61, offs=43)
*/
ATSINSflab(__patsflab_ptr0_succ):
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/pointer.dats({$PATSPRE}/DATS/pointer.dats): 1814(line=61, offs=17) -- 1840(line=61, offs=43)
*/
ATSINSmove(tmpret10, atspre_add_ptr0_bsz(arg0, ATSPMVsizeof(atstyvar_type(a)))) ;

ATSfunbody_end()
ATSreturn(tmpret10) ;
} /* end of [ATSLIB_056_prelude__ptr0_succ__2] */
#endif // end of [TEMPLATE]

/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/pointer.dats: 1808(line=61, offs=11) -- 1840(line=61, offs=43)
*/
/*
local: 
global: ptr0_succ$2$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = a(4026)
tmparg = S2Evar(a(4026))
tmpsub = Some(a(4026) -> S2Ecst(string_type))
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__ptr0_succ__2__1(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret10__1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/pointer.dats({$PATSPRE}/DATS/pointer.dats): 1798(line=61, offs=1) -- 1840(line=61, offs=43)
*/
ATSINSflab(__patsflab_ptr0_succ):
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/pointer.dats({$PATSPRE}/DATS/pointer.dats): 1814(line=61, offs=17) -- 1840(line=61, offs=43)
*/
ATSINSmove(tmpret10__1, atspre_add_ptr0_bsz(arg0, ATSPMVsizeof(atstkind_type(atstype_ptrk)))) ;

ATSfunbody_end()
ATSreturn(tmpret10__1) ;
} /* end of [ATSLIB_056_prelude__ptr0_succ__2__1] */

#if(0)
/*
/Users/sakurai/git/docs/gc/ats_basic/cast.dats: 974(line=26, offs=51) -- 991(line=26, offs=68)
*/
/*
local: fsed_0$0(level=0)
global: fsed_0$0(level=0), array_foreach$fwork$4$0(level=1)
local: 
global: 
*/
ATSextern()
/*
imparg = env(7807)
tmparg = S2Ecst(string_type); S2Evar(env(7807))
tmpsub = None()
*/
atsvoid_t0ype
ATSLIB_056_prelude__array_foreach__fwork__4(atsrefarg1_type(atstkind_type(atstype_ptrk)) arg0, atsrefarg1_type(atstyvar_type(env)) arg1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret15) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/cast.dats: 941(line=26, offs=18) -- 992(line=26, offs=69)
*/
ATSINSflab(__patsflab_array_foreach__fwork):
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/cast.dats: 985(line=26, offs=62) -- 991(line=26, offs=68)
*/
ATSINSmove_void(tmpret15, fsed_0(ATSderef(arg0, atstkind_type(atstype_ptrk)))) ;

ATSfunbody_end()
ATSreturn_void(tmpret15) ;
} /* end of [ATSLIB_056_prelude__array_foreach__fwork__4] */
#endif // end of [TEMPLATE]

#if(0)
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/arrayref.dats: 5111(line=233, offs=3) -- 5199(line=236, offs=4)
*/
/*
local: 
global: arrayref_foreach$5$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(7092)
tmparg = S2Evar(a(7092))
tmpsub = None()
*/
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__arrayref_foreach__5(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_size) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret17, atstkind_t0ype(atstype_size)) ;
// ATStmpdec_void(tmpref18) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/arrayref.dats({$PATSPRE}/DATS/arrayref.dats): 5092(line=232, offs=1) -- 5199(line=236, offs=4)
*/
ATSINSflab(__patsflab_arrayref_foreach):
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/arrayref.dats({$PATSPRE}/DATS/arrayref.dats): 5122(line=233, offs=14) -- 5199(line=236, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/arrayref.dats({$PATSPRE}/DATS/arrayref.dats): 5132(line=234, offs=7) -- 5135(line=234, offs=10)
*/
/*
ATSINStmpdec(tmpref18) ;
*/
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/arrayref.dats({$PATSPRE}/DATS/arrayref.dats): 5144(line=234, offs=19) -- 5146(line=234, offs=21)
*/
ATSINSmove_void(tmpref18, ATSPMVempty()) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/arrayref.dats({$PATSPRE}/DATS/arrayref.dats): 5152(line=235, offs=6) -- 5195(line=235, offs=49)
*/
ATSINSmove(tmpret17, PMVtmpltcst(arrayref_foreach_env<S2Evar(a(7092))><S2Ecst(atsvoid_t0ype)>)(arg0, arg1, ATSPMVrefarg1(ATSPMVptrof_void(tmpref18)))) ;

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/arrayref.dats({$PATSPRE}/DATS/arrayref.dats): 5122(line=233, offs=14) -- 5199(line=236, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret17) ;
} /* end of [ATSLIB_056_prelude__arrayref_foreach__5] */
#endif // end of [TEMPLATE]

/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/arrayref.dats: 5111(line=233, offs=3) -- 5199(line=236, offs=4)
*/
/*
local: 
global: arrayref_foreach$5$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = a(7092)
tmparg = S2Evar(a(7092))
tmpsub = Some(a(7092) -> S2Ecst(string_type))
*/
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__arrayref_foreach__5__1(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_size) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret17__1, atstkind_t0ype(atstype_size)) ;
// ATStmpdec_void(tmpref18__1) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/arrayref.dats({$PATSPRE}/DATS/arrayref.dats): 5092(line=232, offs=1) -- 5199(line=236, offs=4)
*/
ATSINSflab(__patsflab_arrayref_foreach):
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/arrayref.dats({$PATSPRE}/DATS/arrayref.dats): 5122(line=233, offs=14) -- 5199(line=236, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/arrayref.dats({$PATSPRE}/DATS/arrayref.dats): 5132(line=234, offs=7) -- 5135(line=234, offs=10)
*/
/*
ATSINStmpdec(tmpref18) ;
*/
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/arrayref.dats({$PATSPRE}/DATS/arrayref.dats): 5144(line=234, offs=19) -- 5146(line=234, offs=21)
*/
ATSINSmove_void(tmpref18__1, ATSPMVempty()) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/arrayref.dats({$PATSPRE}/DATS/arrayref.dats): 5152(line=235, offs=6) -- 5195(line=235, offs=49)
*/
ATSINSmove(tmpret17__1, ATSLIB_056_prelude__arrayref_foreach_env__7__1(arg0, arg1, ATSPMVrefarg1(ATSPMVptrof_void(tmpref18__1)))) ;

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/arrayref.dats({$PATSPRE}/DATS/arrayref.dats): 5122(line=233, offs=14) -- 5199(line=236, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret17__1) ;
} /* end of [ATSLIB_056_prelude__arrayref_foreach__5__1] */

#if(0)
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/arrayref.dats: 5272(line=241, offs=3) -- 5403(line=245, offs=4)
*/
/*
local: 
global: arrayref_foreach_env$7$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(7097), env(7098)
tmparg = S2Evar(a(7097)); S2Evar(env(7098))
tmpsub = None()
*/
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__arrayref_foreach_env__7(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_size) arg1, atsrefarg1_type(atstyvar_type(env)) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret21, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/arrayref.dats({$PATSPRE}/DATS/arrayref.dats): 5249(line=240, offs=1) -- 5403(line=245, offs=4)
*/
ATSINSflab(__patsflab_arrayref_foreach_env):
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/arrayref.dats({$PATSPRE}/DATS/arrayref.dats): 5288(line=241, offs=19) -- 5403(line=245, offs=4)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/arrayref.dats({$PATSPRE}/DATS/arrayref.dats): 5358(line=244, offs=17) -- 5398(line=244, offs=57)
*/
ATSINSmove(tmpret21, PMVtmpltcst(array_foreach_env<S2Evar(a(7097))><S2Evar(env(7098))>)(ATSPMVrefarg1(ATSPMVcastfn(arrayref_get_viewptr, atstkind_type(atstype_ptrk), arg0)), arg1, ATSPMVrefarg1(arg2))) ;

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/arrayref.dats({$PATSPRE}/DATS/arrayref.dats): 5288(line=241, offs=19) -- 5403(line=245, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret21) ;
} /* end of [ATSLIB_056_prelude__arrayref_foreach_env__7] */
#endif // end of [TEMPLATE]

/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/arrayref.dats: 5272(line=241, offs=3) -- 5403(line=245, offs=4)
*/
/*
local: 
global: arrayref_foreach_env$7$1(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = a(7097), env(7098)
tmparg = S2Evar(a(7097)); S2Evar(env(7098))
tmpsub = Some(a(7097) -> S2Ecst(string_type); env(7098) -> S2Ecst(atsvoid_t0ype))
*/
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__arrayref_foreach_env__7__1(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_size) arg1, atsrefarg1_type(atsvoid_t0ype) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret21__1, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/arrayref.dats({$PATSPRE}/DATS/arrayref.dats): 5249(line=240, offs=1) -- 5403(line=245, offs=4)
*/
ATSINSflab(__patsflab_arrayref_foreach_env):
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/arrayref.dats({$PATSPRE}/DATS/arrayref.dats): 5288(line=241, offs=19) -- 5403(line=245, offs=4)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/arrayref.dats({$PATSPRE}/DATS/arrayref.dats): 5358(line=244, offs=17) -- 5398(line=244, offs=57)
*/
ATSINSmove(tmpret21__1, ATSLIB_056_prelude__array_foreach_env__9__1(ATSPMVrefarg1(ATSPMVcastfn(arrayref_get_viewptr, atstkind_type(atstype_ptrk), arg0)), arg1, ATSPMVrefarg1(arg2))) ;

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/arrayref.dats({$PATSPRE}/DATS/arrayref.dats): 5288(line=241, offs=19) -- 5403(line=245, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret21__1) ;
} /* end of [ATSLIB_056_prelude__arrayref_foreach_env__7__1] */

#if(0)
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats: 9592(line=442, offs=8) -- 10310(line=480, offs=4)
*/
/*
local: 
global: array_foreach_env$9$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(6765), env(6766)
tmparg = S2Evar(a(6765)); S2Evar(env(6766))
tmpsub = None()
*/
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__array_foreach_env__9(atsrefarg1_type(atstyarr_type(atstyvar_type(a))) arg0, atstkind_t0ype(atstype_size) arg1, atsrefarg1_type(atstyvar_type(env)) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret23, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp30, atsrefarg1_type(atstyarr_type(atstyvar_type(a)))) ;
ATStmpdec(tmp31, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 9567(line=441, offs=1) -- 10310(line=480, offs=4)
*/
ATSINSflab(__patsflab_array_foreach_env):
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 9608(line=442, offs=24) -- 10310(line=480, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 10232(line=475, offs=5) -- 10237(line=475, offs=10)
*/
ATSINSmove(tmp30, arg0) ;
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 10257(line=476, offs=9) -- 10290(line=476, offs=42)
*/
ATSINSmove(tmp31, ATSfunclo_fun(PMVd2vfunlab(d2v=loop$2285(1), flab=loop_10$0(level=1)), (atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_size), atsrefarg1_type(atstyvar_type(env))), atstkind_t0ype(atstype_size))(tmp30, arg1, ATSPMVrefarg1(arg2))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 10299(line=479, offs=3) -- 10306(line=479, offs=10)
*/
ATSINSmove(tmpret23, PMVtmpltcst(g1uint_sub<S2Eextkind(atstype_size)>)(arg1, tmp31)) ;

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 9608(line=442, offs=24) -- 10310(line=480, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret23) ;
} /* end of [ATSLIB_056_prelude__array_foreach_env__9] */
#endif // end of [TEMPLATE]

#if(0)
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats: 9655(line=446, offs=5) -- 10207(line=473, offs=4)
*/
/*
local: loop_10$0(level=1)
global: loop_10$0(level=1)
local: 
global: 
*/
ATSstatic()
atstkind_t0ype(atstype_size)
loop_10__10(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_size) arg1, atsrefarg1_type(atstyvar_type(env)) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstkind_type(atstype_ptrk)) ;
ATStmpdec(apy1, atstkind_t0ype(atstype_size)) ;
ATStmpdec(apy2, atsrefarg1_type(atstyvar_type(env))) ;
ATStmpdec(tmpret24, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp25, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp26, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp27) ;
ATStmpdec(tmp28, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp29, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 9655(line=446, offs=5) -- 10207(line=473, offs=4)
*/
ATSINSflab(__patsflab_loop_10):
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 9791(line=455, offs=4) -- 9796(line=455, offs=9)
*/
ATSINSmove(tmp25, PMVtmpltcst(gt_g1uint_int<S2Eextkind(atstype_size)>)(arg1, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 9788(line=455, offs=1) -- 10195(line=471, offs=11)
*/
ATSif(
tmp25
) ATSthen() {
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 9802(line=455, offs=15) -- 10188(line=471, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 9870(line=460, offs=14) -- 9906(line=460, offs=50)
*/
ATSINSmove(tmp26, PMVtmpltcst(array_foreach$cont<S2Evar(a(6765))><S2Evar(env(6766))>)(ATSPMVrefarg1(arg0), ATSPMVrefarg1(arg2))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 9912(line=462, offs=3) -- 10166(line=470, offs=6)
*/
ATSif(
tmp26
) ATSthen() {
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 9925(line=462, offs=16) -- 10101(line=468, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 9942(line=463, offs=14) -- 9979(line=463, offs=51)
*/
ATSINSmove_void(tmp27, PMVtmpltcst(array_foreach$fwork<S2Evar(a(6765))><S2Evar(env(6766))>)(ATSPMVrefarg1(arg0), ATSPMVrefarg1(arg2))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 10006(line=464, offs=27) -- 10021(line=464, offs=42)
*/
ATSINSmove(tmp28, PMVtmpltcst(ptr1_succ<S2Evar(a(6765))>)(arg0)) ;

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 10024(line=464, offs=45) -- 10030(line=464, offs=51)
*/
ATSINSmove(tmp29, PMVtmpltcst(g1uint_pred<S2Eextkind(atstype_size)>)(arg1)) ;

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 9994(line=464, offs=15) -- 10037(line=464, offs=58)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, tmp28) ;
ATSINSmove_tlcal(apy1, tmp29) ;
ATSINSmove_tlcal(apy2, ATSPMVrefarg1(arg2)) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSargmove_tlcal(arg2, apy2) ;
ATSINSfgoto(__patsflab_loop_10) ;
ATStailcal_end()

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 9925(line=462, offs=16) -- 10101(line=468, offs=6)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 10159(line=469, offs=49) -- 10160(line=469, offs=50)
*/
ATSINSmove(tmpret24, arg1) ;
} /* ATSendif */
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 9802(line=455, offs=15) -- 10188(line=471, offs=4)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 10194(line=471, offs=10) -- 10195(line=471, offs=11)
*/
ATSINSmove(tmpret24, arg1) ;
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret24) ;
} /* end of [loop_10__10] */
#endif // end of [TEMPLATE]

/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats: 9592(line=442, offs=8) -- 10310(line=480, offs=4)
*/
/*
local: 
global: array_foreach_env$9$1(level=3)
local: 
global: 
*/
ATSstatic()
/*
imparg = a(6765), env(6766)
tmparg = S2Evar(a(6765)); S2Evar(env(6766))
tmpsub = Some(a(6765) -> S2Ecst(string_type); env(6766) -> S2Ecst(atsvoid_t0ype))
*/
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__array_foreach_env__9__1(atsrefarg1_type(atstyarr_type(atstkind_type(atstype_ptrk))) arg0, atstkind_t0ype(atstype_size) arg1, atsrefarg1_type(atsvoid_t0ype) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret23__1, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp30__1, atsrefarg1_type(atstyarr_type(atstkind_type(atstype_ptrk)))) ;
ATStmpdec(tmp31__1, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 9567(line=441, offs=1) -- 10310(line=480, offs=4)
*/
ATSINSflab(__patsflab_array_foreach_env):
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 9608(line=442, offs=24) -- 10310(line=480, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 10232(line=475, offs=5) -- 10237(line=475, offs=10)
*/
ATSINSmove(tmp30__1, arg0) ;
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 10257(line=476, offs=9) -- 10290(line=476, offs=42)
*/
ATSINSmove(tmp31__1, loop_10__10__1(tmp30__1, arg1, ATSPMVrefarg1(arg2))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 10299(line=479, offs=3) -- 10306(line=479, offs=10)
*/
ATSINSmove(tmpret23__1, atspre_g1uint_sub_size(arg1, tmp31__1)) ;

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 9608(line=442, offs=24) -- 10310(line=480, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret23__1) ;
} /* end of [ATSLIB_056_prelude__array_foreach_env__9__1] */

/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats: 9655(line=446, offs=5) -- 10207(line=473, offs=4)
*/
/*
local: loop_10$1(level=4)
global: loop_10$1(level=4)
local: 
global: 
*/
ATSstatic()
atstkind_t0ype(atstype_size)
loop_10__10__1(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_size) arg1, atsrefarg1_type(atsvoid_t0ype) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstkind_type(atstype_ptrk)) ;
ATStmpdec(apy1, atstkind_t0ype(atstype_size)) ;
ATStmpdec(apy2, atsrefarg1_type(atsvoid_t0ype)) ;
ATStmpdec(tmpret24__1, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp25__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp26__1, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp27__1) ;
ATStmpdec(tmp28__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp29__1, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 9655(line=446, offs=5) -- 10207(line=473, offs=4)
*/
ATSINSflab(__patsflab_loop_10):
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 9791(line=455, offs=4) -- 9796(line=455, offs=9)
*/
ATSINSmove(tmp25__1, ATSLIB_056_prelude__gt_g1uint_int__13__1(arg1, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 9788(line=455, offs=1) -- 10195(line=471, offs=11)
*/
ATSif(
tmp25__1
) ATSthen() {
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 9802(line=455, offs=15) -- 10188(line=471, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 9870(line=460, offs=14) -- 9906(line=460, offs=50)
*/
ATSINSmove(tmp26__1, ATSLIB_056_prelude__array_foreach__cont__17__1(ATSPMVrefarg1(arg0), ATSPMVrefarg1(arg2))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 9912(line=462, offs=3) -- 10166(line=470, offs=6)
*/
ATSif(
tmp26__1
) ATSthen() {
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 9925(line=462, offs=16) -- 10101(line=468, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 9942(line=463, offs=14) -- 9979(line=463, offs=51)
*/
ATSINSmove_void(tmp27__1, ATSLIB_056_prelude__array_foreach__fwork__4__1(ATSPMVrefarg1(arg0), ATSPMVrefarg1(arg2))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 10006(line=464, offs=27) -- 10021(line=464, offs=42)
*/
ATSINSmove(tmp28__1, ATSLIB_056_prelude__ptr1_succ__20__1(arg0)) ;

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 10024(line=464, offs=45) -- 10030(line=464, offs=51)
*/
ATSINSmove(tmp29__1, atspre_g1uint_pred_size(arg1)) ;

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 9994(line=464, offs=15) -- 10037(line=464, offs=58)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, tmp28__1) ;
ATSINSmove_tlcal(apy1, tmp29__1) ;
ATSINSmove_tlcal(apy2, ATSPMVrefarg1(arg2)) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSargmove_tlcal(arg2, apy2) ;
ATSINSfgoto(__patsflab_loop_10) ;
ATStailcal_end()

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 9925(line=462, offs=16) -- 10101(line=468, offs=6)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 10159(line=469, offs=49) -- 10160(line=469, offs=50)
*/
ATSINSmove(tmpret24__1, arg1) ;
} /* ATSendif */
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 9802(line=455, offs=15) -- 10188(line=471, offs=4)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 10194(line=471, offs=10) -- 10195(line=471, offs=11)
*/
ATSINSmove(tmpret24__1, arg1) ;
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret24__1) ;
} /* end of [loop_10__10__1] */

#if(0)
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/integer.dats: 30712(line=860, offs=15) -- 30754(line=860, offs=57)
*/
/*
local: 
global: gt_g1uint_int$13$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4565)
tmparg = S2Evar(tk(4565))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g1uint_int__13(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret41, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp42, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 30698(line=860, offs=1) -- 30754(line=860, offs=57)
*/
ATSINSflab(__patsflab_gt_g1uint_int):
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 30739(line=860, offs=42) -- 30752(line=860, offs=55)
*/
ATSINSmove(tmp42, PMVtmpltcst(g1int2uint<S2Eextkind(atstype_int), S2Evar(tk(4565))>)(arg1)) ;

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 30721(line=860, offs=24) -- 30754(line=860, offs=57)
*/
ATSINSmove(tmpret41, PMVtmpltcst(g1uint_gt<S2Evar(tk(4565))>)(arg0, tmp42)) ;

ATSfunbody_end()
ATSreturn(tmpret41) ;
} /* end of [ATSLIB_056_prelude__gt_g1uint_int__13] */
#endif // end of [TEMPLATE]

/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/integer.dats: 30712(line=860, offs=15) -- 30754(line=860, offs=57)
*/
/*
local: 
global: gt_g1uint_int$13$1(level=5)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4565)
tmparg = S2Evar(tk(4565))
tmpsub = Some(tk(4565) -> S2Eextkind(atstype_size))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g1uint_int__13__1(atstkind_t0ype(atstype_size) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret41__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp42__1, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 30698(line=860, offs=1) -- 30754(line=860, offs=57)
*/
ATSINSflab(__patsflab_gt_g1uint_int):
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 30739(line=860, offs=42) -- 30752(line=860, offs=55)
*/
ATSINSmove(tmp42__1, atspre_g1int2uint_int_size(arg1)) ;

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 30721(line=860, offs=24) -- 30754(line=860, offs=57)
*/
ATSINSmove(tmpret41__1, atspre_g1uint_gt_size(arg0, tmp42__1)) ;

ATSfunbody_end()
ATSreturn(tmpret41__1) ;
} /* end of [ATSLIB_056_prelude__gt_g1uint_int__13__1] */

#if(0)
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats: 10400(line=485, offs=20) -- 10415(line=485, offs=35)
*/
/*
local: 
global: array_foreach$cont$17$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(6771), env(6772)
tmparg = S2Evar(a(6771)); S2Evar(env(6772))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__array_foreach__cont__17(atsrefarg1_type(atstyvar_type(a)) arg0, atsrefarg1_type(atstyvar_type(env)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret45, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 10381(line=485, offs=1) -- 10415(line=485, offs=35)
*/
ATSINSflab(__patsflab_array_foreach__cont):
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 10411(line=485, offs=31) -- 10415(line=485, offs=35)
*/
ATSINSmove(tmpret45, ATSPMVbool_true()) ;
ATSfunbody_end()
ATSreturn(tmpret45) ;
} /* end of [ATSLIB_056_prelude__array_foreach__cont__17] */
#endif // end of [TEMPLATE]

/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats: 10400(line=485, offs=20) -- 10415(line=485, offs=35)
*/
/*
local: 
global: array_foreach$cont$17$1(level=5)
local: 
global: 
*/
ATSstatic()
/*
imparg = a(6771), env(6772)
tmparg = S2Evar(a(6771)); S2Evar(env(6772))
tmpsub = Some(a(6771) -> S2Ecst(string_type); env(6772) -> S2Ecst(atsvoid_t0ype))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__array_foreach__cont__17__1(atsrefarg1_type(atstkind_type(atstype_ptrk)) arg0, atsrefarg1_type(atsvoid_t0ype) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret45__1, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 10381(line=485, offs=1) -- 10415(line=485, offs=35)
*/
ATSINSflab(__patsflab_array_foreach__cont):
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats({$PATSPRE}/DATS/array.dats): 10411(line=485, offs=31) -- 10415(line=485, offs=35)
*/
ATSINSmove(tmpret45__1, ATSPMVbool_true()) ;
ATSfunbody_end()
ATSreturn(tmpret45__1) ;
} /* end of [ATSLIB_056_prelude__array_foreach__cont__17__1] */

/*
/Users/sakurai/git/docs/gc/ats_basic/cast.dats: 974(line=26, offs=51) -- 991(line=26, offs=68)
*/
/*
local: fsed_0$0(level=0)
global: fsed_0$0(level=0), array_foreach$fwork$4$1(level=5)
local: 
global: 
*/
ATSstatic()
/*
imparg = env(7807)
tmparg = S2Ecst(string_type); S2Evar(env(7807))
tmpsub = Some(env(7807) -> S2Ecst(atsvoid_t0ype))
*/
atsvoid_t0ype
ATSLIB_056_prelude__array_foreach__fwork__4__1(atsrefarg1_type(atstkind_type(atstype_ptrk)) arg0, atsrefarg1_type(atsvoid_t0ype) arg1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret15__1) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/cast.dats: 941(line=26, offs=18) -- 992(line=26, offs=69)
*/
ATSINSflab(__patsflab_array_foreach__fwork):
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/cast.dats: 985(line=26, offs=62) -- 991(line=26, offs=68)
*/
ATSINSmove_void(tmpret15__1, fsed_0(ATSderef(arg0, atstkind_type(atstype_ptrk)))) ;

ATSfunbody_end()
ATSreturn_void(tmpret15__1) ;
} /* end of [ATSLIB_056_prelude__array_foreach__fwork__4__1] */

#if(0)
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/pointer.dats: 2321(line=84, offs=15) -- 2373(line=85, offs=47)
*/
/*
local: 
global: ptr1_succ$20$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(4036)
tmparg = S2Evar(a(4036))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__ptr1_succ__20(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret48, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp49, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/pointer.dats({$PATSPRE}/DATS/pointer.dats): 2307(line=84, offs=1) -- 2373(line=85, offs=47)
*/
ATSINSflab(__patsflab_ptr1_succ):
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/pointer.dats({$PATSPRE}/DATS/pointer.dats): 2356(line=85, offs=30) -- 2371(line=85, offs=45)
*/
ATSINSmove(tmp49, PMVtmpltcst(ptr0_succ<S2Evar(a(4036))>)(arg0)) ;

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/pointer.dats({$PATSPRE}/DATS/pointer.dats): 2329(line=85, offs=3) -- 2373(line=85, offs=47)
*/
ATSINSmove(tmpret48, ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), tmp49)) ;
ATSfunbody_end()
ATSreturn(tmpret48) ;
} /* end of [ATSLIB_056_prelude__ptr1_succ__20] */
#endif // end of [TEMPLATE]

/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/pointer.dats: 2321(line=84, offs=15) -- 2373(line=85, offs=47)
*/
/*
local: 
global: ptr1_succ$20$1(level=5)
local: 
global: 
*/
ATSstatic()
/*
imparg = a(4036)
tmparg = S2Evar(a(4036))
tmpsub = Some(a(4036) -> S2Ecst(string_type))
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__ptr1_succ__20__1(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret48__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp49__1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/pointer.dats({$PATSPRE}/DATS/pointer.dats): 2307(line=84, offs=1) -- 2373(line=85, offs=47)
*/
ATSINSflab(__patsflab_ptr1_succ):
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/pointer.dats({$PATSPRE}/DATS/pointer.dats): 2356(line=85, offs=30) -- 2371(line=85, offs=45)
*/
ATSINSmove(tmp49__1, ATSLIB_056_prelude__ptr0_succ__2__2(arg0)) ;

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/pointer.dats({$PATSPRE}/DATS/pointer.dats): 2329(line=85, offs=3) -- 2373(line=85, offs=47)
*/
ATSINSmove(tmpret48__1, ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), tmp49__1)) ;
ATSfunbody_end()
ATSreturn(tmpret48__1) ;
} /* end of [ATSLIB_056_prelude__ptr1_succ__20__1] */

/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/pointer.dats: 1808(line=61, offs=11) -- 1840(line=61, offs=43)
*/
/*
local: 
global: ptr0_succ$2$2(level=6)
local: 
global: 
*/
ATSstatic()
/*
imparg = a(4026)
tmparg = S2Evar(a(4026))
tmpsub = Some(a(4026) -> S2Ecst(string_type))
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__ptr0_succ__2__2(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret10__2, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/pointer.dats({$PATSPRE}/DATS/pointer.dats): 1798(line=61, offs=1) -- 1840(line=61, offs=43)
*/
ATSINSflab(__patsflab_ptr0_succ):
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/pointer.dats({$PATSPRE}/DATS/pointer.dats): 1814(line=61, offs=17) -- 1840(line=61, offs=43)
*/
ATSINSmove(tmpret10__2, atspre_add_ptr0_bsz(arg0, ATSPMVsizeof(atstkind_type(atstype_ptrk)))) ;

ATSfunbody_end()
ATSreturn(tmpret10__2) ;
} /* end of [ATSLIB_056_prelude__ptr0_succ__2__2] */

/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_Users_057_sakurai_057_git_057_docs_057_gc_057_ats_basic_057_cast_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_Users_057_sakurai_057_git_057_docs_057_gc_057_ats_basic_057_cast_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_Users_057_sakurai_057_git_057_docs_057_gc_057_ats_basic_057_cast_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_Users_057_sakurai_057_git_057_docs_057_gc_057_ats_basic_057_cast_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_Users_057_sakurai_057_git_057_docs_057_gc_057_ats_basic_057_cast_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime_memalloc.c"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_runtime2_dats.c"
#ifndef _ATS_CCOMP_RUNTIME_TRYWITH_NONE
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_TRYWITH_NONE */
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_RUNTIME_NONE */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057_Users_057_sakurai_057_git_057_docs_057_gc_057_ats_basic_057_cast_056_dats__dynload() ;
ATSmainats_argc_argv_0(argc, argv, err) ;
return (err) ;
} /* end of [main] */

/* ****** ****** */

/* end-of-compilation-unit */
