/*
**
** The C code is generated by ATS/Postiats
** The starting compilation time is: 2015-10-19: 21h:12m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER
//
#include _ATS_CCOMP_PRELUDE_USER
//
#endif /* _ATS_CCOMP_PRELUDE_USER */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2
//
#include _ATS_CCOMP_PRELUDE_USER2
//
#endif /* _ATS_CCOMP_PRELUDE_USER2 */

/*
staload-prologues(beg)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/integer_ptr.dats: 1639(line=51, offs=1) -- 1678(line=51, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/integer_fixed.dats: 1641(line=51, offs=1) -- 1680(line=51, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/char.dats: 1610(line=48, offs=1) -- 1649(line=48, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/memory.dats: 1410(line=38, offs=1) -- 1449(line=39, offs=32)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/string.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/strptr.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/strptr.dats: 1671(line=52, offs=1) -- 1718(line=52, offs=48)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats: 1613(line=48, offs=1) -- 1652(line=48, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats: 1675(line=52, offs=1) -- 1722(line=52, offs=48)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats: 1745(line=56, offs=1) -- 1783(line=56, offs=39)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libc/SATS/stdio.sats: 1898(line=62, offs=1) -- 1940(line=64, offs=27)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats: 1861(line=61, offs=1) -- 1901(line=61, offs=41)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libc/sys/SATS/stat.sats: 1390(line=36, offs=1) -- 1431(line=38, offs=3)
*/

#include "libc/sys/CATS/stat.cats"
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libc/sys/SATS/stat.sats: 1712(line=52, offs=1) -- 1754(line=53, offs=35)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats: 15323(line=844, offs=1) -- 15353(line=844, offs=31)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libc/SATS/stdio.sats: 1898(line=62, offs=1) -- 1940(line=64, offs=27)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/list.dats: 1527(line=44, offs=1) -- 1566(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/list.dats: 1567(line=45, offs=1) -- 1613(line=45, offs=47)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/list_vt.dats: 1536(line=44, offs=1) -- 1575(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/stream.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/stream_vt.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/tostring.dats: 1528(line=44, offs=1) -- 1567(line=45, offs=32)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/checkast.dats: 1531(line=44, offs=1) -- 1570(line=45, offs=32)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libats/ML/DATS/list0.dats: 1444(line=40, offs=1) -- 1483(line=40, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libats/ML/DATS/list0.dats: 1506(line=44, offs=1) -- 1541(line=44, offs=36)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libats/ML/DATS/list0.dats: 1542(line=45, offs=1) -- 1577(line=45, offs=36)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libats/ML/SATS/filebas.sats: 1525(line=41, offs=1) -- 1560(line=41, offs=36)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstkind_type(atstype_ptrk) atslab__0 ;
} postiats_tysum_0 ;
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstkind_type(atstype_ptrk) atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_1 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atslib_fopen)
ATSdyncst_mac(atspre_gt_ptr1_intz)
ATSdyncst_mac(atspre_file_mode_r)
ATSdyncst_extfun(ATSLIB_056_libats_056_ML__fileref_get_lines_stringlst, (atstkind_type(atstype_ptrk)), atstype_boxed) ;
ATSdyncst_mac(atspre_fprint_string)
ATSdyncst_mac(atspre_fprint_int)
ATSdyncst_mac(atspre_fprint_newline)
ATSdyncst_mac(atspre_g0int_add_int)
ATSdyncst_mac(atspre_FILE_stdout)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
ATSstatmpdec(statmp0, atstype_boxed) ;
ATSstatmpdec(statmp7, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(statmp8, atstype_boxed) ;
// ATSstatmpdec_void(statmp18) ;
#if(0)
#if(0)
ATSextern()
atstype_boxed
ATSLIB_056_prelude__fileref_open_opt__0(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstype_boxed
ATSLIB_056_prelude__fileref_open_opt__0__1(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)) ;

ATSstatic()
atsvoid_t0ype
loop_2(atstkind_type(atstype_ptrk), atstype_boxed, atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atsvoid_t0ype
mainats_void_0() ;
#endif // end of [QUALIFIED]

#if(0)
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats: 4920(line=241, offs=3) -- 5279(line=269, offs=4)
*/
/*
local: 
global: fileref_open_opt$0$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstype_boxed
ATSLIB_056_prelude__fileref_open_opt__0(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret1, atstype_boxed) ;
ATStmpdec(tmp2, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp3, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 4901(line=240, offs=1) -- 5279(line=269, offs=4)
*/
ATSINSflab(__patsflab_fileref_open_opt):
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 4933(line=241, offs=16) -- 5279(line=269, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 4951(line=244, offs=8) -- 4974(line=244, offs=31)
*/
ATSINSmove(tmp2, atslib_fopen(arg0, arg1)) ;

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 4987(line=246, offs=9) -- 5015(line=246, offs=37)
*/
ATSINSmove(tmp3, atspre_gt_ptr1_intz(ATSPMVcastfn(FILEptr2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(tmp2)), ATSPMVi0nt(0))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5025(line=250, offs=1) -- 5255(line=267, offs=4)
*/
ATSif(
tmp3
) ATSthen() {
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5039(line=252, offs=6) -- 5132(line=259, offs=4)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5095(line=258, offs=3) -- 5116(line=258, offs=24)
*/

/*
#LINCONSTATUS==0
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret1, postiats_tysum_0) ;
#if(0)
ATSINSstore_con1_tag(tmpret1, 0) ;
#endif
ATSINSstore_con1_ofs(tmpret1, postiats_tysum_0, atslab__0, ATSPMVcastfn(FILEptr_refize, atstkind_type(atstype_ptrk), tmp2)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5039(line=252, offs=6) -- 5132(line=259, offs=4)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5214(line=266, offs=3) -- 5240(line=266, offs=29)
*/

ATSINSmove_nil(tmpret1) ;

} /* ATSendif */
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 4933(line=241, offs=16) -- 5279(line=269, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret1) ;
} /* end of [ATSLIB_056_prelude__fileref_open_opt__0] */
#endif // end of [TEMPLATE]

/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats: 4920(line=241, offs=3) -- 5279(line=269, offs=4)
*/
/*
local: 
global: fileref_open_opt$0$1(level=0)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstype_boxed
ATSLIB_056_prelude__fileref_open_opt__0__1(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret1__1, atstype_boxed) ;
ATStmpdec(tmp2__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp3__1, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 4901(line=240, offs=1) -- 5279(line=269, offs=4)
*/
ATSINSflab(__patsflab_fileref_open_opt):
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 4933(line=241, offs=16) -- 5279(line=269, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 4951(line=244, offs=8) -- 4974(line=244, offs=31)
*/
ATSINSmove(tmp2__1, atslib_fopen(arg0, arg1)) ;

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 4987(line=246, offs=9) -- 5015(line=246, offs=37)
*/
ATSINSmove(tmp3__1, atspre_gt_ptr1_intz(ATSPMVcastfn(FILEptr2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(tmp2__1)), ATSPMVi0nt(0))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5025(line=250, offs=1) -- 5255(line=267, offs=4)
*/
ATSif(
tmp3__1
) ATSthen() {
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5039(line=252, offs=6) -- 5132(line=259, offs=4)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5095(line=258, offs=3) -- 5116(line=258, offs=24)
*/

/*
#LINCONSTATUS==0
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret1__1, postiats_tysum_0) ;
#if(0)
ATSINSstore_con1_tag(tmpret1__1, 0) ;
#endif
ATSINSstore_con1_ofs(tmpret1__1, postiats_tysum_0, atslab__0, ATSPMVcastfn(FILEptr_refize, atstkind_type(atstype_ptrk), tmp2__1)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5039(line=252, offs=6) -- 5132(line=259, offs=4)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5214(line=266, offs=3) -- 5240(line=266, offs=29)
*/

ATSINSmove_nil(tmpret1__1) ;

} /* ATSendif */
/*
emit_instr: loc0 = /usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 4933(line=241, offs=16) -- 5279(line=269, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret1__1) ;
} /* end of [ATSLIB_056_prelude__fileref_open_opt__0__1] */

/*
/Users/sakurai/git/docs/gc/ats_basic/file.dats: 423(line=14, offs=7) -- 598(line=17, offs=84)
*/
/*
local: loop_2$0(level=0)
global: loop_2$0(level=0)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
loop_2(atstkind_type(atstype_ptrk) arg0, atstype_boxed arg1, atstkind_t0ype(atstype_int) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstkind_type(atstype_ptrk)) ;
ATStmpdec(apy1, atstype_boxed) ;
ATStmpdec(apy2, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmpret9) ;
ATStmpdec(tmp10, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp11, atstype_boxed) ;
// ATStmpdec_void(tmp12) ;
// ATStmpdec_void(tmp13) ;
// ATStmpdec_void(tmp14) ;
// ATStmpdec_void(tmp15) ;
// ATStmpdec_void(tmp16) ;
ATStmpdec(tmp17, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/file.dats: 423(line=14, offs=7) -- 598(line=17, offs=84)
*/
ATSINSflab(__patsflab_loop_2):
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/file.dats: 483(line=15, offs=5) -- 598(line=17, offs=84)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/file.dats: 501(line=16, offs=7) -- 508(line=16, offs=14)
*/
ATSINSlab(__atstmplab0):
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/file.dats: 442(line=14, offs=26) -- 444(line=14, offs=28)
*/
ATSifthen(ATSCKptriscons(arg1)) { ATSINSgoto(__atstmplab3) ; } ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/file.dats: 508(line=16, offs=14) -- 508(line=16, offs=14)
*/
ATSINSlab(__atstmplab1):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/file.dats: 512(line=16, offs=18) -- 514(line=16, offs=20)
*/
ATSINSmove_void(tmpret9, ATSPMVempty()) ;
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/file.dats: 521(line=17, offs=7) -- 534(line=17, offs=20)
*/
ATSINSlab(__atstmplab2):
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/file.dats: 442(line=14, offs=26) -- 444(line=14, offs=28)
*/
#if(0)
ATSifthen(ATSCKptrisnull(arg1)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/file.dats: 534(line=17, offs=20) -- 534(line=17, offs=20)
*/
ATSINSlab(__atstmplab3):
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/file.dats: 528(line=17, offs=14) -- 529(line=17, offs=15)
*/
ATSINSmove(tmp10, ATSSELcon(arg1, postiats_tysum_1, atslab__0)) ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/file.dats: 531(line=17, offs=17) -- 533(line=17, offs=19)
*/
ATSINSmove(tmp11, ATSSELcon(arg1, postiats_tysum_1, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/file.dats: 538(line=17, offs=24) -- 576(line=17, offs=62)
*/
ATSINSmove_void(tmp12, atspre_fprint_string(arg0, ATSPMVstring("line("))) ;

/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/file.dats: 538(line=17, offs=24) -- 576(line=17, offs=62)
*/
ATSINSmove_void(tmp13, atspre_fprint_int(arg0, arg2)) ;

/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/file.dats: 538(line=17, offs=24) -- 576(line=17, offs=62)
*/
ATSINSmove_void(tmp14, atspre_fprint_string(arg0, ATSPMVstring(") = "))) ;

/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/file.dats: 538(line=17, offs=24) -- 576(line=17, offs=62)
*/
ATSINSmove_void(tmp15, atspre_fprint_string(arg0, tmp10)) ;

/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/file.dats: 538(line=17, offs=24) -- 576(line=17, offs=62)
*/
ATSINSmove_void(tmp16, atspre_fprint_newline(arg0)) ;

/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/file.dats: 593(line=17, offs=79) -- 596(line=17, offs=82)
*/
ATSINSmove(tmp17, atspre_g0int_add_int(arg2, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/file.dats: 578(line=17, offs=64) -- 597(line=17, offs=83)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, arg0) ;
ATSINSmove_tlcal(apy1, tmp11) ;
ATSINSmove_tlcal(apy2, tmp17) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSargmove_tlcal(arg2, apy2) ;
ATSINSfgoto(__patsflab_loop_2) ;
ATStailcal_end()

ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn_void(tmpret9) ;
} /* end of [loop_2] */

/*
/Users/sakurai/git/docs/gc/ats_basic/file.dats: 657(line=21, offs=17) -- 664(line=21, offs=24)
*/
/*
local: 
global: mainats_void_0$4$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
mainats_void_0()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret19) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/file.dats: 651(line=21, offs=11) -- 664(line=21, offs=24)
*/
ATSINSflab(__patsflab_main_void_0):
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/file.dats: 662(line=21, offs=22) -- 664(line=21, offs=24)
*/
ATSINSmove_void(tmpret19, ATSPMVempty()) ;
ATSfunbody_end()
ATSreturn_void(tmpret19) ;
} /* end of [mainats_void_0] */

/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_Users_057_sakurai_057_git_057_docs_057_gc_057_ats_basic_057_file_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_Users_057_sakurai_057_git_057_docs_057_gc_057_ats_basic_057_file_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_Users_057_sakurai_057_git_057_docs_057_gc_057_ats_basic_057_file_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_Users_057_sakurai_057_git_057_docs_057_gc_057_ats_basic_057_file_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_Users_057_sakurai_057_git_057_docs_057_gc_057_ats_basic_057_file_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/file.dats: 294(line=10, offs=10) -- 639(line=19, offs=2)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/file.dats: 319(line=11, offs=24) -- 364(line=11, offs=69)
*/
ATSINSmove(statmp0, ATSLIB_056_prelude__fileref_open_opt__0__1(ATSPMVstring("./file.dats"), atspre_file_mode_r)) ;

/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/file.dats: 302(line=11, offs=7) -- 316(line=11, offs=21)
*/
ATSifthen(ATSCKptrisnull(statmp0)) { ATSINScaseof_fail("/Users/sakurai/git/docs/gc/ats_basic/file.dats: 302(line=11, offs=7) -- 364(line=11, offs=69)") ; } ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/file.dats: 311(line=11, offs=16) -- 315(line=11, offs=20)
*/
ATSINSmove(statmp7, ATSSELcon(statmp0, postiats_tysum_0, atslab__0)) ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/file.dats: 302(line=11, offs=7) -- 316(line=11, offs=21)
*/
ATSINSfreecon(statmp0) ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/file.dats: 379(line=12, offs=15) -- 412(line=12, offs=48)
*/
ATSINSmove(statmp8, ATSLIB_056_libats_056_ML__fileref_get_lines_stringlst(statmp7)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/file.dats: 610(line=18, offs=12) -- 637(line=18, offs=39)
*/
ATSINSmove_void(statmp18, loop_2(atspre_FILE_stdout, statmp8, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/file.dats: 294(line=10, offs=10) -- 639(line=19, offs=2)
*/
/*
INSletpop()
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime_memalloc.c"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_runtime2_dats.c"
#ifndef _ATS_CCOMP_RUNTIME_TRYWITH_NONE
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_TRYWITH_NONE */
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_RUNTIME_NONE */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057_Users_057_sakurai_057_git_057_docs_057_gc_057_ats_basic_057_file_056_dats__dynload() ;
ATSmainats_void_0(err) ;
return (err) ;
} /* end of [main] */

/* ****** ****** */

/* end-of-compilation-unit */
