/*
**
** The C code is generated by ATS/Postiats
** The starting compilation time is: 2015-10-19: 21h:12m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER
//
#include _ATS_CCOMP_PRELUDE_USER
//
#endif /* _ATS_CCOMP_PRELUDE_USER */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2
//
#include _ATS_CCOMP_PRELUDE_USER2
//
#endif /* _ATS_CCOMP_PRELUDE_USER2 */

/*
staload-prologues(beg)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/integer_ptr.dats: 1639(line=51, offs=1) -- 1678(line=51, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/integer_fixed.dats: 1641(line=51, offs=1) -- 1680(line=51, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/char.dats: 1610(line=48, offs=1) -- 1649(line=48, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/memory.dats: 1410(line=38, offs=1) -- 1449(line=39, offs=32)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/string.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/strptr.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/strptr.dats: 1671(line=52, offs=1) -- 1718(line=52, offs=48)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats: 1613(line=48, offs=1) -- 1652(line=48, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats: 1675(line=52, offs=1) -- 1722(line=52, offs=48)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats: 1745(line=56, offs=1) -- 1783(line=56, offs=39)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libc/SATS/stdio.sats: 1898(line=62, offs=1) -- 1940(line=64, offs=27)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats: 1861(line=61, offs=1) -- 1901(line=61, offs=41)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libc/sys/SATS/stat.sats: 1390(line=36, offs=1) -- 1431(line=38, offs=3)
*/

#include "libc/sys/CATS/stat.cats"
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libc/sys/SATS/stat.sats: 1712(line=52, offs=1) -- 1754(line=53, offs=35)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/filebas.dats: 15323(line=844, offs=1) -- 15353(line=844, offs=31)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libc/SATS/stdio.sats: 1898(line=62, offs=1) -- 1940(line=64, offs=27)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/list.dats: 1527(line=44, offs=1) -- 1566(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/list.dats: 1567(line=45, offs=1) -- 1613(line=45, offs=47)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/list_vt.dats: 1536(line=44, offs=1) -- 1575(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/stream.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/stream_vt.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/tostring.dats: 1528(line=44, offs=1) -- 1567(line=45, offs=32)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/prelude/DATS/checkast.dats: 1531(line=44, offs=1) -- 1570(line=45, offs=32)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libats/ML/DATS/list0.dats: 1444(line=40, offs=1) -- 1483(line=40, offs=40)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libats/ML/DATS/list0.dats: 1506(line=44, offs=1) -- 1541(line=44, offs=36)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libats/ML/DATS/list0.dats: 1542(line=45, offs=1) -- 1577(line=45, offs=36)
*/
/*
/usr/local/Cellar/ats2-postiats/0.2.0/lib/ats2-postiats-0.2.0/libats/ML/SATS/list0.sats: 1665(line=47, offs=1) -- 1700(line=47, offs=36)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstkind_t0ype(atstype_int) atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_0 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_print_int)
ATSdyncst_mac(atspre_print_newline)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
ATSstatic()
atsvoid_t0ype
printls_0(atstype_boxed) ;

#if(0)
ATSextern()
atsvoid_t0ype
mainats_void_0() ;
#endif // end of [QUALIFIED]

/*
/Users/sakurai/git/docs/gc/ats_basic/list.dats: 262(line=8, offs=5) -- 412(line=16, offs=6)
*/
/*
local: printls_0$0(level=0)
global: printls_0$0(level=0)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
printls_0(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstype_boxed) ;
// ATStmpdec_void(tmpret0) ;
ATStmpdec(tmp1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp2, atstype_boxed) ;
// ATStmpdec_void(tmp3) ;
// ATStmpdec_void(tmp4) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 262(line=8, offs=5) -- 412(line=16, offs=6)
*/
ATSINSflab(__patsflab_printls_0):
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 303(line=9, offs=9) -- 406(line=15, offs=14)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 321(line=10, offs=7) -- 328(line=10, offs=14)
*/
ATSINSlab(__atstmplab0):
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 270(line=8, offs=13) -- 272(line=8, offs=15)
*/
ATSifthen(ATSCKptrisnull(arg0)) { ATSINSgoto(__atstmplab2) ; } ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 328(line=10, offs=14) -- 328(line=10, offs=14)
*/
ATSINSlab(__atstmplab1):
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 321(line=10, offs=7) -- 322(line=10, offs=8)
*/
ATSINSmove(tmp1, ATSSELcon(arg0, postiats_tysum_0, atslab__0)) ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 326(line=10, offs=12) -- 328(line=10, offs=14)
*/
ATSINSmove(tmp2, ATSSELcon(arg0, postiats_tysum_0, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 352(line=12, offs=9) -- 362(line=12, offs=19)
*/
ATSINSmove_void(tmp3, atspre_print_int(tmp1)) ;

/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 352(line=12, offs=9) -- 362(line=12, offs=19)
*/
ATSINSmove_void(tmp4, atspre_print_newline()) ;

/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 372(line=13, offs=9) -- 382(line=13, offs=19)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, tmp2) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSfgoto(__patsflab_printls_0) ;
ATStailcal_end()

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 400(line=15, offs=8) -- 400(line=15, offs=8)
*/
ATSINSlab(__atstmplab2):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 404(line=15, offs=12) -- 406(line=15, offs=14)
*/
ATSINSmove_void(tmpret0, ATSPMVempty()) ;
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn_void(tmpret0) ;
} /* end of [printls_0] */

/*
/Users/sakurai/git/docs/gc/ats_basic/list.dats: 430(line=18, offs=17) -- 593(line=23, offs=2)
*/
/*
local: printls_0$0(level=0)
global: printls_0$0(level=0), mainats_void_0$1$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
mainats_void_0()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret5) ;
// ATStmpdec_void(tmp6) ;
ATStmpdec(tmp7, atstype_boxed) ;
// ATStmpdec_void(tmp8) ;
ATStmpdec(tmp9, atstype_boxed) ;
ATStmpdec(tmp10, atstype_boxed) ;
// ATStmpdec_void(tmp11) ;
ATStmpdec(tmp12, atstype_boxed) ;
ATStmpdec(tmp13, atstype_datconptr) ;
ATStmpdec(tmp14, atstype_datconptr) ;
ATStmpdec(tmp15, atstype_boxed) ;
ATStmpdec(tmp16, atstype_boxed) ;
ATStmpdec(tmp17, atstype_boxed) ;
ATStmpdec(tmp18, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 424(line=18, offs=11) -- 593(line=23, offs=2)
*/
ATSINSflab(__patsflab_main_void_0):
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 435(line=18, offs=22) -- 593(line=23, offs=2)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 456(line=19, offs=20) -- 462(line=19, offs=26)
*/

ATSINSmove_nil(tmp7) ;

/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 448(line=19, offs=12) -- 463(line=19, offs=27)
*/
ATSINSmove_void(tmp6, printls_0(tmp7)) ;

/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 491(line=20, offs=28) -- 497(line=20, offs=34)
*/

ATSINSmove_nil(tmp10) ;

/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 483(line=20, offs=20) -- 498(line=20, offs=35)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmp9, postiats_tysum_0) ;
#if(0)
ATSINSstore_con1_tag(tmp9, 1) ;
#endif
ATSINSstore_con1_ofs(tmp9, postiats_tysum_0, atslab__0, ATSPMVi0nt(1)) ;
ATSINSstore_con1_ofs(tmp9, postiats_tysum_0, atslab__1, tmp10) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 475(line=20, offs=12) -- 499(line=20, offs=36)
*/
ATSINSmove_void(tmp8, printls_0(tmp9)) ;

/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 533(line=21, offs=34) -- 553(line=21, offs=54)
*/
/*
ATSINStmpdec(tmp12) ;
*/
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 533(line=21, offs=34) -- 553(line=21, offs=54)
*/
ATSINSmove(tmp14, ATSPMVptrof(tmp12)) ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 539(line=21, offs=40) -- 540(line=21, offs=41)
*/
ATSINSpmove_list_cons(tmp14, atstkind_t0ype(atstype_int)) ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 539(line=21, offs=40) -- 540(line=21, offs=41)
*/
ATSINSmove_list_phead(tmp13, tmp14, atstkind_t0ype(atstype_int)) ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 539(line=21, offs=40) -- 540(line=21, offs=41)
*/
ATSINSpmove(tmp13, atstkind_t0ype(atstype_int), ATSPMVi0nt(0)) ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 539(line=21, offs=40) -- 540(line=21, offs=41)
*/
ATSINSmove_list_ptail(tmp14, tmp14, atstkind_t0ype(atstype_int)) ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 542(line=21, offs=43) -- 543(line=21, offs=44)
*/
ATSINSpmove_list_cons(tmp14, atstkind_t0ype(atstype_int)) ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 542(line=21, offs=43) -- 543(line=21, offs=44)
*/
ATSINSmove_list_phead(tmp13, tmp14, atstkind_t0ype(atstype_int)) ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 542(line=21, offs=43) -- 543(line=21, offs=44)
*/
ATSINSpmove(tmp13, atstkind_t0ype(atstype_int), ATSPMVi0nt(2)) ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 542(line=21, offs=43) -- 543(line=21, offs=44)
*/
ATSINSmove_list_ptail(tmp14, tmp14, atstkind_t0ype(atstype_int)) ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 545(line=21, offs=46) -- 546(line=21, offs=47)
*/
ATSINSpmove_list_cons(tmp14, atstkind_t0ype(atstype_int)) ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 545(line=21, offs=46) -- 546(line=21, offs=47)
*/
ATSINSmove_list_phead(tmp13, tmp14, atstkind_t0ype(atstype_int)) ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 545(line=21, offs=46) -- 546(line=21, offs=47)
*/
ATSINSpmove(tmp13, atstkind_t0ype(atstype_int), ATSPMVi0nt(4)) ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 545(line=21, offs=46) -- 546(line=21, offs=47)
*/
ATSINSmove_list_ptail(tmp14, tmp14, atstkind_t0ype(atstype_int)) ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 548(line=21, offs=49) -- 549(line=21, offs=50)
*/
ATSINSpmove_list_cons(tmp14, atstkind_t0ype(atstype_int)) ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 548(line=21, offs=49) -- 549(line=21, offs=50)
*/
ATSINSmove_list_phead(tmp13, tmp14, atstkind_t0ype(atstype_int)) ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 548(line=21, offs=49) -- 549(line=21, offs=50)
*/
ATSINSpmove(tmp13, atstkind_t0ype(atstype_int), ATSPMVi0nt(6)) ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 548(line=21, offs=49) -- 549(line=21, offs=50)
*/
ATSINSmove_list_ptail(tmp14, tmp14, atstkind_t0ype(atstype_int)) ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 551(line=21, offs=52) -- 552(line=21, offs=53)
*/
ATSINSpmove_list_cons(tmp14, atstkind_t0ype(atstype_int)) ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 551(line=21, offs=52) -- 552(line=21, offs=53)
*/
ATSINSmove_list_phead(tmp13, tmp14, atstkind_t0ype(atstype_int)) ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 551(line=21, offs=52) -- 552(line=21, offs=53)
*/
ATSINSpmove(tmp13, atstkind_t0ype(atstype_int), ATSPMVi0nt(8)) ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 551(line=21, offs=52) -- 552(line=21, offs=53)
*/
ATSINSmove_list_ptail(tmp14, tmp14, atstkind_t0ype(atstype_int)) ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 533(line=21, offs=34) -- 553(line=21, offs=54)
*/
ATSINSpmove_list_nil(tmp14) ;
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 511(line=21, offs=12) -- 555(line=21, offs=56)
*/
ATSINSmove_void(tmp11, printls_0(ATSPMVcastfn(list0_of_list, atstype_boxed, tmp12))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 584(line=22, offs=29) -- 590(line=22, offs=35)
*/

ATSINSmove_nil(tmp18) ;

/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 581(line=22, offs=26) -- 590(line=22, offs=35)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmp17, postiats_tysum_0) ;
#if(0)
ATSINSstore_con1_tag(tmp17, 1) ;
#endif
ATSINSstore_con1_ofs(tmp17, postiats_tysum_0, atslab__0, ATSPMVi0nt(3)) ;
ATSINSstore_con1_ofs(tmp17, postiats_tysum_0, atslab__1, tmp18) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 578(line=22, offs=23) -- 590(line=22, offs=35)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmp16, postiats_tysum_0) ;
#if(0)
ATSINSstore_con1_tag(tmp16, 1) ;
#endif
ATSINSstore_con1_ofs(tmp16, postiats_tysum_0, atslab__0, ATSPMVi0nt(2)) ;
ATSINSstore_con1_ofs(tmp16, postiats_tysum_0, atslab__1, tmp17) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 575(line=22, offs=20) -- 590(line=22, offs=35)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmp15, postiats_tysum_0) ;
#if(0)
ATSINSstore_con1_tag(tmp15, 1) ;
#endif
ATSINSstore_con1_ofs(tmp15, postiats_tysum_0, atslab__0, ATSPMVi0nt(1)) ;
ATSINSstore_con1_ofs(tmp15, postiats_tysum_0, atslab__1, tmp16) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 567(line=22, offs=12) -- 591(line=22, offs=36)
*/
ATSINSmove_void(tmpret5, printls_0(tmp15)) ;

/*
emit_instr: loc0 = /Users/sakurai/git/docs/gc/ats_basic/list.dats: 435(line=18, offs=22) -- 593(line=23, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret5) ;
} /* end of [mainats_void_0] */

/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_Users_057_sakurai_057_git_057_docs_057_gc_057_ats_basic_057_list_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_Users_057_sakurai_057_git_057_docs_057_gc_057_ats_basic_057_list_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_Users_057_sakurai_057_git_057_docs_057_gc_057_ats_basic_057_list_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_Users_057_sakurai_057_git_057_docs_057_gc_057_ats_basic_057_list_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_Users_057_sakurai_057_git_057_docs_057_gc_057_ats_basic_057_list_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime_memalloc.c"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_runtime2_dats.c"
#ifndef _ATS_CCOMP_RUNTIME_TRYWITH_NONE
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_TRYWITH_NONE */
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_RUNTIME_NONE */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057_Users_057_sakurai_057_git_057_docs_057_gc_057_ats_basic_057_list_056_dats__dynload() ;
ATSmainats_void_0(err) ;
return (err) ;
} /* end of [main] */

/* ****** ****** */

/* end-of-compilation-unit */
