all:
	sbt "~runMain xxml.main"
test:
	sbt "~runMain tes.main"

tes2: tes2.scala
	sbt "~runMain tes2.main"
tes3: tes3.scala
	sbt "~runMain tes3.main"
clean:
	rm -rf target xxml xxml1_1 xxml1_2 xxml1_3 xxml2_1 xxml2_2 xxml2_3 xxml3_1 xxml3_2

